# Uncomment the next line to define a global platform for your project

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

# platform :ios, '9.0'
platform :ios, '15.0'

target 'iosApp' do
  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp/'
end
